// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

/*
Package pb3 is a generated protocol buffer package.

It is generated from these files:
	data.proto

It has these top-level messages:
	F1
	F2
	Resp
	Req
*/
package pb3

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type F1 struct {
	Seq  int64  `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *F1) Reset()                    { *m = F1{} }
func (m *F1) String() string            { return proto.CompactTextString(m) }
func (*F1) ProtoMessage()               {}
func (*F1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *F1) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *F1) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type F2 struct {
	AllVals []string `protobuf:"bytes,1,rep,name=all_vals,json=allVals" json:"all_vals,omitempty"`
}

func (m *F2) Reset()                    { *m = F2{} }
func (m *F2) String() string            { return proto.CompactTextString(m) }
func (*F2) ProtoMessage()               {}
func (*F2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *F2) GetAllVals() []string {
	if m != nil {
		return m.AllVals
	}
	return nil
}

type Resp struct {
	Succ bool `protobuf:"varint,1,opt,name=succ" json:"succ,omitempty"`
	F1   *F1  `protobuf:"bytes,2,opt,name=f1" json:"f1,omitempty"`
	F2   *F2  `protobuf:"bytes,3,opt,name=f2" json:"f2,omitempty"`
}

func (m *Resp) Reset()                    { *m = Resp{} }
func (m *Resp) String() string            { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()               {}
func (*Resp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Resp) GetSucc() bool {
	if m != nil {
		return m.Succ
	}
	return false
}

func (m *Resp) GetF1() *F1 {
	if m != nil {
		return m.F1
	}
	return nil
}

func (m *Resp) GetF2() *F2 {
	if m != nil {
		return m.F2
	}
	return nil
}

type Req struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Req) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*F1)(nil), "pb3.F1")
	proto.RegisterType((*F2)(nil), "pb3.F2")
	proto.RegisterType((*Resp)(nil), "pb3.Resp")
	proto.RegisterType((*Req)(nil), "pb3.Req")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Svc service

type SvcClient interface {
	Get(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type svcClient struct {
	cc *grpc.ClientConn
}

func NewSvcClient(cc *grpc.ClientConn) SvcClient {
	return &svcClient{cc}
}

func (c *svcClient) Get(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := grpc.Invoke(ctx, "/pb3.Svc/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Svc service

type SvcServer interface {
	Get(context.Context, *Req) (*Resp, error)
}

func RegisterSvcServer(s *grpc.Server, srv SvcServer) {
	s.RegisterService(&_Svc_serviceDesc, srv)
}

func _Svc_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SvcServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb3.Svc/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SvcServer).Get(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Svc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb3.Svc",
	HandlerType: (*SvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Svc_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}

func init() { proto.RegisterFile("data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0xcd, 0xce, 0xe9, 0x25, 0xa3, 0x85, 0x4c, 0x73, 0x51, 0x04, 0xc3, 0xda, 0x04, 0x8b,
	0xc0, 0x6e, 0xfe, 0x81, 0x45, 0x6c, 0xac, 0x46, 0xb0, 0xb0, 0x91, 0x4d, 0xdc, 0x34, 0x2e, 0xdc,
	0xc6, 0x8d, 0x01, 0xff, 0xbd, 0xec, 0x60, 0x71, 0xdd, 0x07, 0x6f, 0xde, 0xc7, 0x3c, 0xc4, 0x4f,
	0xb7, 0xba, 0x2e, 0x7e, 0x1f, 0xd7, 0x23, 0x41, 0x1c, 0x7b, 0xfd, 0x88, 0x6a, 0x30, 0x74, 0x8d,
	0x90, 0xfc, 0x52, 0x17, 0x4d, 0xd1, 0x02, 0x67, 0x24, 0xc2, 0x5d, 0x3e, 0xad, 0x55, 0x53, 0xb4,
	0x57, 0x2c, 0xac, 0xef, 0x51, 0x0d, 0x96, 0x6e, 0xb0, 0x74, 0x21, 0x7c, 0x6c, 0x2e, 0xa4, 0xba,
	0x68, 0xa0, 0xad, 0x78, 0xef, 0x42, 0x78, 0x73, 0x21, 0xe9, 0x17, 0xdc, 0xb1, 0x4f, 0x31, 0x97,
	0xd3, 0xcf, 0x34, 0x89, 0xaf, 0x64, 0x61, 0x3a, 0xa0, 0x9a, 0x8d, 0xe8, 0x2e, 0xed, 0xbe, 0x8b,
	0x63, 0xdf, 0x0d, 0x86, 0xd5, 0x6c, 0x24, 0xb0, 0x35, 0x9c, 0x06, 0x96, 0xd5, 0x6c, 0xf5, 0x01,
	0x81, 0xfd, 0x92, 0x7f, 0xfb, 0xf2, 0xbf, 0xe2, 0xaa, 0x38, 0xa3, 0x7d, 0x40, 0x78, 0xdd, 0x26,
	0xba, 0x43, 0x78, 0xf6, 0x2b, 0x95, 0xd2, 0x61, 0xbf, 0xdc, 0x56, 0xff, 0x94, 0xa2, 0x3e, 0x7b,
	0x3a, 0x7f, 0xcf, 0xfb, 0xc6, 0x0b, 0xd9, 0xda, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x63,
	0xc5, 0x4e, 0xf9, 0x00, 0x00, 0x00,
}
