// automatically generated by the FlatBuffers compiler, do not modify

package flat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Req struct {
	_tab flatbuffers.Table
}

func GetRootAsReq(buf []byte, offset flatbuffers.UOffsetT) *Req {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Req{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Req) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Req) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Req) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ReqAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func ReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
